tests: make runtest more robust
runtest doesn't appear to fail on MacOS,
even though it should. Adding and checking
an error.log should fix that.

Signed-off-by: Timothy Day <tday141@gmail.com>

diff --git a/runtest b/runtest
--- a/runtest
+++ b/runtest
@@ -10,11 +10,22 @@
 trap 'runtest-failure' ERR
 
 #
-# Function called on failure
+# Function called on failure, used to log
+# errors
 #
 function runtest-failure() {
-    echo "Sourcing script failed!"
+    echo "Sourcing script failed!" > ./error.log
 }
 
-set -e
+# Remove old error log, if there
+rm -f ./error.log
+
+set -Ee
 source ./general/tims-tools
+
+# If we have an error.log, we had an error
+if [[ -f ./error.log ]]; then
+    cat ./error.log
+    rm -f ./error.log
+    exit 1
+fi
